/**
 * Test-only helpers that build a byte-accurate Token-2022 account carrying the
 * ConfidentialTransferAccount extension, with ciphertexts generated by the real
 * `@solana/zk-sdk` WASM under known keys. Not part of the published bundle.
 */
import * as zk from "@solana/zk-sdk/node";
import {
  ACCOUNT_TYPE_OFFSET,
  AccountType,
  BASE_ACCOUNT_LEN,
  CT_ACCOUNT_LEN,
  CtAccountLayout as L,
  ExtensionType,
  TLV_START,
} from "../state/extension.js";

export interface FixtureKeys {
  elgamalSecret: Uint8Array;
  elgamalPubkey: Uint8Array;
  aeKey: Uint8Array;
}

/** Deterministically derive a key set from a single seed byte. */
export function makeKeys(seedByte = 1): FixtureKeys {
  const kp = zk.ElGamalKeypair.fromSeed(new Uint8Array(32).fill(seedByte));
  const keys: FixtureKeys = {
    elgamalSecret: kp.secret().toBytes(),
    elgamalPubkey: kp.pubkey().toBytes(),
    aeKey: zk.AeKey.fromSeed(new Uint8Array(16).fill(seedByte)).toBytes(),
  };
  kp.free();
  return keys;
}

export interface FixtureOptions {
  keys: FixtureKeys;
  /** Low 16 bits of the pending balance. */
  pendingLo?: bigint;
  /** Bits [16,48) of the pending balance. */
  pendingHi?: bigint;
  /** Available balance (encoded into both the ElGamal and AES ciphertexts). */
  available?: bigint;
  mint?: Uint8Array;
  approved?: boolean;
  pendingBalanceCreditCounter?: bigint;
  /** Prepend an unrelated zero-length extension to exercise the TLV walker. */
  withLeadingExtension?: boolean;
}

function writeU16LE(buf: Uint8Array, offset: number, value: number): void {
  buf[offset] = value & 0xff;
  buf[offset + 1] = (value >> 8) & 0xff;
}

function writeU64LE(buf: Uint8Array, offset: number, value: bigint): void {
  let v = value;
  for (let i = 0; i < 8; i++) {
    buf[offset + i] = Number(v & 0xffn);
    v >>= 8n;
  }
}

function encryptElGamal(pubkey: Uint8Array, amount: bigint): Uint8Array {
  const pk = zk.ElGamalPubkey.fromBytes(pubkey);
  const ct = pk.encryptU64(amount);
  const bytes = ct.toBytes();
  pk.free();
  ct.free();
  return bytes;
}

function encryptAe(aeKey: Uint8Array, amount: bigint): Uint8Array {
  const key = zk.AeKey.fromBytes(aeKey);
  const ct = key.encrypt(amount);
  const bytes = ct.toBytes();
  key.free();
  ct.free();
  return bytes;
}

/** Build the 295-byte ConfidentialTransferAccount extension payload. */
export function buildExtensionPayload(opts: FixtureOptions): Uint8Array {
  const { keys } = opts;
  const ext = new Uint8Array(CT_ACCOUNT_LEN);

  ext[L.approved] = opts.approved === false ? 0 : 1;
  ext.set(keys.elgamalPubkey, L.elgamalPubkey);
  ext.set(encryptElGamal(keys.elgamalPubkey, opts.pendingLo ?? 0n), L.pendingBalanceLo);
  ext.set(encryptElGamal(keys.elgamalPubkey, opts.pendingHi ?? 0n), L.pendingBalanceHi);
  ext.set(encryptElGamal(keys.elgamalPubkey, opts.available ?? 0n), L.availableBalance);
  ext.set(encryptAe(keys.aeKey, opts.available ?? 0n), L.decryptableAvailableBalance);
  ext[L.allowConfidentialCredits] = 1;
  ext[L.allowNonConfidentialCredits] = 1;
  writeU64LE(ext, L.pendingBalanceCreditCounter, opts.pendingBalanceCreditCounter ?? 0n);
  writeU64LE(ext, L.maximumPendingBalanceCreditCounter, 65536n);
  writeU64LE(ext, L.expectedPendingBalanceCreditCounter, 0n);
  writeU64LE(ext, L.actualPendingBalanceCreditCounter, 0n);
  return ext;
}

/** Build a complete Token-2022 account buffer with the confidential extension. */
export function buildConfidentialAccount(opts: FixtureOptions): Uint8Array {
  const payload = buildExtensionPayload(opts);
  const leading = opts.withLeadingExtension ? 4 : 0; // type+len of a zero-length ext
  const total = TLV_START + leading + 4 + payload.length;
  const data = new Uint8Array(total);

  if (opts.mint) data.set(opts.mint.subarray(0, 32), 0);
  data[ACCOUNT_TYPE_OFFSET] = AccountType.Account;

  let cursor = TLV_START;
  if (opts.withLeadingExtension) {
    // ImmutableOwner (type 7), zero-length — the walker must skip it.
    writeU16LE(data, cursor, 7);
    writeU16LE(data, cursor + 2, 0);
    cursor += 4;
  }
  writeU16LE(data, cursor, ExtensionType.ConfidentialTransferAccount);
  writeU16LE(data, cursor + 2, payload.length);
  data.set(payload, cursor + 4);

  return data;
}

export { BASE_ACCOUNT_LEN };
