/**
 * GOLDEN FIXTURE — a real Token-2022 account that RECEIVED a confidential
 * transfer on public devnet (agave 4.1.0-rc.1), captured 2026-06-17.
 *
 * The faucet account sent 10 tokens confidentially via the
 * version-matched spl-token-cli 5.6.1; the amount is hidden on-chain and only
 * the recipient's (HKDF-SHA512-derived) key decrypts it. Throwaway test keys.
 *
 * Recipient: GDFyNfj6ZbBrXWzsZuFvBmab6V8Y3geYZrkdhnzJ9z9M
 * Transfer tx: 41zf4Sk1mANE92UoiHL4jkiBfeNgDDsLzq3fVPQPrGubfNPb7i5db1bCdSe6i2iSB6y48FQMrGbJoJLfXWMsgfjr
 */
export const DEVNET_TRANSFER_ACCOUNT = "GDFyNfj6ZbBrXWzsZuFvBmab6V8Y3geYZrkdhnzJ9z9M";
export const DEVNET_TRANSFER_TX = "41zf4Sk1mANE92UoiHL4jkiBfeNgDDsLzq3fVPQPrGubfNPb7i5db1bCdSe6i2iSB6y48FQMrGbJoJLfXWMsgfjr";
export const DEVNET_TRANSFER_AE_KEY_HEX = "80d840d5968c23a749ead7ae7bfccb1f";
export const DEVNET_TRANSFER_AMOUNT = 10000000000n;

export const DEVNET_TRANSFER_ACCOUNT_BASE64 =
  "96NdyWIcHdgDC2erXDYTKZ4w14HdoYwzZem2NdQrQx7xFvz0jll6OHaFRCd7rBwnMQejgDocqlW85d0PjUW7RgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgcAAAAFACcBAfLgqjg4Rdmn3D8Uk6rJqrh/Ll6KFgtdwHZw1CUcwIMVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4ERnQ9/RUKviT6f/vbW9ghtQzdrvDhckpJpLGkakgHLgwWr6Q6fQCqhtk+f9DNx5i2Y3+4NdXjYUcvyd16CIggJHPs4L/kHjgKEG0sdzwMjdo36CdmhrNIoAg/MFimHJw28wjAQEAAAAAAAAAAAAAAQAAAAAAAQAAAAAAAAABAAAAAAAAAA==";
