/**
 * GOLDEN FIXTURE — a real Token-2022 confidential account, captured live from a
 * surfpool mainnet-fork after `spl-token configure-confidential-transfer-account`
 * (spl-token-cli 5.5.0, Agave 4.0.1). Locks our byte-layout parser against output
 * from the actual on-chain program. Balances are zero (a freshly configured
 * account); this validates every field offset, not decryption of a nonzero value.
 *
 * Account: GMsoaTCsm4g2w5873uKgWYLBKw1e7HNPrTtmPjR3qzNw
 * Do not edit by hand — regenerate with scripts/repro-confidential-flow.sh.
 */
export const REAL_CONFIGURED_ACCOUNT_BASE64 =
  "TFO8JSP1USa5EVQIZbe41paQrKuzByPpRD2S2CzSfSzzJBJAGH+KxTwjPtQE0U9ZJwIOER5fOY6dNqxxn6679gAQpdToAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgcAAAAFACcBAeDooIJ/asGn06Sskbv/EEuATgKIL2N+Q8A+N6LmBl8+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0XcB2BQxpV1uRn3LIipZpxnG++ZsB42NAUdl1e3h8lPmaLw7AQEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
